on: [push]

name: build

jobs:
  build:
    name: Build docker image 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: philips-software/docker-ci-scripts@docker-organization-optional
      with:
        dockerfile: 1
        image-name: test
        tags: 'latest 1'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_REGISTRY: 'artifactory.test.io'  
